# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='message',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='view',
            name='name',
            field=models.CharField(default='me', max_length=15),
        ),
    ]
