# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20160405_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='view',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
