# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20160406_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='view',
            options={},
        ),
        migrations.RemoveField(
            model_name='view',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='view',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
